server:
  port: ${PORT:8080}
logging:
  level:
    root: INFO
spring:
  profiles:
#    active: test
    active: ${PRODUCTION:developing}

---
spring:
  profiles: developing
  datasource:
    url: jdbc:h2:file:./src/main/resources/myDB/myDB
    username: sa
    password:

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yaml

  h2:
    console:
      enabled: true
      path: /h2console/
      settings:
        web-allow-others: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
---
spring:
  profiles: production
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yaml

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
---
spring:
  profiles: test
  datasource:
    initialization-mode: always
    platform: postgres

    url: jdbc:postgresql://containers-us-west-80.railway.app:8058/railway
    username: postgres
    password: ${PASSWORD}


  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yaml

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate