server:
  port: ${PORT:7337}
logging:
  level:
    root: INFO
spring:
  profiles:
#    active: postgres
    active: ${PRODUCTION:developing}
---
spring:
  profiles: developing
  datasource:
    url: jdbc:h2:mem:myDB
    username: sa
    password:

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yaml

  h2:
    console:
      enabled: true
      path: /h2console/
      settings:
        web-allow-others: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
---
spring:
  profiles: production
  datasource:
    engine: django.db.backends.postgresql
    name: ${PGDATABASE}
#    url: jdbc:${DATABASE_URL}
    username: ${PGUSER}
    password: ${PGPASSWORD}
    host: ${PGHOST}
    port: ${PGPORT}

  liquibase:
    enabled: false
    change-log: classpath:db/changelog/changelog-master.yaml

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create
---
spring:
  profiles: postgres
  datasource:
    initialization-mode: always
    platform: postgres
#    engine: django.db.backends.postgresql
#    name: railway
    url: jdbc:postgresql://postgres:rPuQnmyi4wY5F1f7cdEP@containers-us-west-29.railway.app:7337/railway
    username: postgres
    password: rPuQnmyi4wY5F1f7cdEP
#    host: containers-us-west-29.railway.app
#    port: 7337

  liquibase:
    enabled: false
    change-log: classpath:db/changelog/changelog-master.yaml

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true