server:
  port: ${PORT:8092}
logging:
  level:
    root: INFO
spring:
  profiles:
#    active: myTests
    active: ${PRODUCTION:development}

base-url: api
jwt-token-secret: ${SECRET:lkrfslrekjfalecmasieuro3wurhnsjkcafjsefljashkfaewjkfljsrhkjgjsfndjtgtdlgjsghsjdyr}
jwt-token-expired: 3600000
ACCESS_TOKEN: ${SECRET_ACCESS_TOKEN:kjgkjgkjgkgjgjygkujgfjyf}

springdoc:
  swagger-ui:
    path: /swagger-ui.html