logging:
  level:
    root: INFO
spring:
  profiles:
    active: ${DEV:production}
---
spring:
  profiles: development
#  datasource:
#    url: jdbc:h2:mem:myDB
#    username: sa
#    password:

  liquibase:
    enabled: false
    change-log: classpath:db/changelog/changelog-master.yaml

  h2:
    console:
      enabled: true
      path: /h2console/
      settings:
        web-allow-others: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
---
spring:
  profiles: production
  datasource:
    url: postgresql://postgres:rPuQnmyi4wY5F1f7cdEP@containers-us-west-29.railway.app:7337/railway
    username: postgres
    password: rPuQnmyi4wY5F1f7cdEP

  liquibase:
    enabled: false
    change-log: classpath:db/changelog/changelog-master.yaml

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
---
spring:
  profiles: postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: docker

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yaml

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
