server:
  port: ${PORT:8092}
logging:
  level:
    root: INFO
spring:
  profiles:
#    active: myTests
    active: ${PRODUCTION:development}

base-url: api
jwt-token-secret: MySecret0ScxWoc0CW0pjOccGLsS8X8p9oThXdJ8CzK3HzjwEkjhfkjhglkjglulkh
jwt-token-expired: 3600000